### ISSUE TITLE
Stack Trace get swallowed

### ISSUE THREAD

**Issue by noisyscanner** [kanekotic/express-exception-handler#2]
Hey this seems super useful but if I log the `error.stack` in my Express middleware I just get the following:
```
18:18:50 ExceptionCustom: Error: error message
    at continueToErrorMiddleware (/Users/brad/code/node_modules/express-exception-handler/lib/wrap.js:17:15)
    at routePromise.catch.err (/Users/brad/code/node_modules/express-exception-handler/lib/wrap.js:8:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Is there a way to get the original stack trace, or original thrown error? Cheers

**Comment by kanekotic** [comment]
that is a great observation 👍 , I had it discarded because thought it might be a bit of leak of internals. Nevertheles I think you are right for development this is important. 
Thanks for the PR also I have merged it, and i will release a minor version with your changes.

**Comment by kanekotic** [comment]
@noisyscanner your changes should be reflected now in version `1.1.0`
